import { afterEach, expect, it, vi } from 'vitest';
import { tasksApi, routinesApi, tagsApi, statisticsApi } from '@/modules/focus/tasks';
import { authApi } from '@/modules/auth/auth';
afterEach(() => vi.unstubAllGlobals());
it('preserva los contratos y usa PATCH para edición', async () => {
  const fetchMock = vi.fn().mockResolvedValue({ ok: true, json: async () => ({}) });
  vi.stubGlobal('fetch', fetchMock);
  await tasksApi.list();
  await tasksApi.get(1);
  await tasksApi.create('Tarea', 'Alta');
  await tasksApi.update(1, { action: 'start' });
  await routinesApi.list();
  await routinesApi.create('Rutina', 'Media');
  await routinesApi.update(1, { active: false });
  await routinesApi.history(1);
  await tagsApi.list();
  await tagsApi.create('Personal', '#7c3aed');
  await statisticsApi.get('2026-09-17', '2026-09-18', 'tag');
  await statisticsApi.get('2026-09-17', '2026-09-18');
  await authApi.me();
  await authApi.status();
  await authApi.login('santi@example.test', 'password');
  await authApi.register('Santiago Giraldo', 'santi@example.test', 'password', 'setup');
  await authApi.logout();
  await authApi.forgot('santi@example.test');
  await authApi.reset({ password: 'new', token: 'token' });
  expect(fetchMock.mock.calls.filter((call) => call[1].method === 'PATCH')).toHaveLength(2);
  expect(fetchMock.mock.calls.every((call) => call[0].startsWith('/api/v1/'))).toBe(true);
});
